# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moovdriver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for moovdriver
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'moovdriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'moovdriver-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for moovdriver-tvOS

  target 'moovdriver-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
